name: App Test

on: 
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./code/

        strategy:
            matrix:
                python-version: [3.11.1]

        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}
            
            - name: Set up NodeJs
              uses: actions/setup-node@v3

            - name: install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r ./script/requirements.txt

            - name: install testing package
              run:   
                npm install jest

            - name: install jsdom and jquery
              run: |
                npm install jsdom
                npm install jquery
            
            - name: run tests
              run: 
                    npx jest ./web_page/js/tests/Article.tests.js
                    npx jest ./web_page/js/tests/Paragraph.tests.js
                    npx jest ./web_page/js/tests/Scraper.tests.js
                    npx jest ./web_page/js/tests/Source.tests.js
            

                
                

            
